# Alembic Configuration File

[alembic]
# Path to migration scripts
script_location = alembic

# Template used to generate migration files
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s

# Timezone used for migration file names
timezone = UTC

# Database URL from config
sqlalchemy.url = mysql+pymysql://root:87j766h@localhost:3306/mysql_analysis
